### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by donaldbraman** [civictechdc/dc-campaign-finance-scraper#3]
```
donalds-air:wrangler dbraman$ python3 download.py 
Traceback (most recent call last):
  File "download.py", line 36, in <module>
expenditures = scraper.records_with_office_and_election_year(from_date=start_date, to_date=end_date, report_type='exp')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/utils.py", line 52, in wrapper
return_output = f(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/scraper.py", line 98, in records_with_office_and_election_year
return records(from_date, to_date, report_type).map(add_election_columns)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/tablib.py", line 7, in map
self.dict = list(map(function, self.dict))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/scraper.py", line 94, in add_election_columns
utils.year_from_date(record["Date of Receipt"])
KeyError: 'Date of Receipt'
```

Problem may be that expenditures don't have "Date of Receipt"; instead they have "Date of Expenditure".  So when it calls this function, it can't find a matching column: 

```
def add_election_columns(record):
    record['Office'], record["Election Year"] = election_of_committee(
        record["Committee Name"],
        utils.year_from_date(record["Date of Receipt"])
    )
    return record

return records(from_date, to_date, report_type).map(add_election_columns)
```

**Comment by donaldbraman** [comment]
Most recent error: 

```
Traceback (most recent call last):
  File "download.py", line 38, in <module>
    expenditures = scraper.records_with_office_and_election_year(from_date=start_date, to_date=end_date, report_type='exp')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/utils.py", line 52, in wrapper
    return_output = f(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/scraper.py", line 98, in records_with_office_and_election_year
    return records(from_date, to_date, report_type).map(add_election_columns)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/utils.py", line 52, in wrapper
    return_output = f(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/scraper.py", line 60, in records
    return tablib.Dataset(*rows, headers=headers).map(normalize_record)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/tablib.py", line 7, in map
    self.dict = list(map(function, self.dict))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dc_campaign_finance_scraper/scraper.py", line 57, in normalize_record
    record['Candidate Name'] = record['Candidate Name'].strip()
KeyError: 'Candidate Name'
```

**Comment by donaldbraman** [comment]
will open as new issue with more information
